apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
  labels:
    app: fleetman-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-webapp
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: fleetman-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32517
  type: NodePort
